version: '3.4'

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jekyll
    command: bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --trace"
    ports:
      - "4000:4000"
    volumes:
      - .:/home/user