# Process Automation
- version: 1.0
  pages:
    - title: 'Introduction'
      path: '/process-automation/latest/'
    - title: 'Model'
      pages:
        - title: 'Overview'
          path: '/process-automation/latest/model/'
        - title: 'Projects'
          path: '/process-automation/latest/model/projects/'
        - title: 'Processes'
          pages:
            - title: 'Overview'
              path: '/process-automation/latest/model/processes/'
            - title: 'BPMN'
              path: '/process-automation/latest/model/processes/bpmn/'
        - title: 'Forms'
          path: '/process-automation/latest/model/forms/'
        - title: 'Decision tables'
          path: '/process-automation/latest/model/decisions/'
        - title: 'Connectors'
          pages:
            - title: 'Overview'
              path: '/process-automation/latest/model/connectors/'
            - title: 'Content connector'
              path: '/process-automation/latest/model/connectors/content/'
            - title: 'Generate a document'
              path: '/process-automation/latest/model/connectors/generate/'
            - title: 'DocuSign'
              path: '/process-automation/latest/model/connectors/docusign/'
            - title: 'Email'
              path: '/process-automation/latest/model/connectors/email/'
            - title: 'REST'
              path: '/process-automation/latest/model/connectors/rest/'
            - title: 'Amazon Web Services'
              path: '/process-automation/latest/model/connectors/aws/'
            - title: 'Slack'
              path: '/process-automation/latest/model/connectors/slack/'
            - title: 'Twilio'
              path: '/process-automation/latest/model/connectors/twilio/'
            - title: 'Salesforce'
              path: '/process-automation/latest/model/connectors/salesforce/'
        - title: 'Content models'
          path: '/process-automation/latest/model/content-models/'



