# Process Automation
- version: 1.0
  pages:
    - title: 'Introduction'
      path: '/process-automation/latest/'
    - title: 'Model'
      pages:
        - title: 'Overview'
          path: '/process-automation/latest/model/'
        - title: 'Projects'
          path: '/process-automation/latest/model/projects/'
        - title: 'Processes'
          pages:
            - title: 'Overview'
              path: '/process-automation/latest/model/processes/'
            - title: 'BPMN'
              path: '/process-automation/latest/model/processes/bpmn/'
            - title: 'Engine events'
              path: '/process-automation/latest/model/processes/events/'
        - title: 'Forms'
          path: '/process-automation/latest/model/forms/'
        - title: 'Connectors'
          pages:
            - title: 'Overview'
              path: '/process-automation/latest/model/connectors/'
            - title: 'Amazon Web Services'
              path: '/process-automation/latest/model/connectors/aws/'
            - title: 'Content connector'
              path: '/process-automation/latest/model/connectors/content/'
            - title: 'Generate a document'
              path: '/process-automation/latest/model/connectors/generate/'
            - title: 'DocuSign'
              path: '/process-automation/latest/model/connectors/docusign/'
            - title: 'Email'
              path: '/process-automation/latest/model/connectors/email/'
            - title: 'REST'
              path: '/process-automation/latest/model/connectors/rest/'
            - title: 'Database'
              path: '/process-automation/latest/model/connectors/database/'
            - title: 'Slack'
              path: '/process-automation/latest/model/connectors/slack/'
            - title: 'Twilio'
              path: '/process-automation/latest/model/connectors/twilio/'
            - title: 'Salesforce'
              path: '/process-automation/latest/model/connectors/salesforce/'
            - title: 'Microsoft Outlook'
              path: '/process-automation/latest/model/connectors/outlook/'
            - title: 'Microsoft Teams'
              path: '/process-automation/latest/model/connectors/teams/'
        - title: 'Authentication'
          path: '/process-automation/latest/model/authentication/'
        - title: 'Decision tables'
          path: '/process-automation/latest/model/decisions/'
        - title: 'User interfaces'
          path: '/process-automation/latest/model/interfaces/'
        - title: 'Files'
          path: '/process-automation/latest/model/files/'
        - title: 'Scripts'
          path: '/process-automation/latest/model/scripts/'
        - title: 'Triggers'
          path: '/process-automation/latest/model/triggers/'
        - title: 'Content models'
          path: '/process-automation/latest/model/content-models/'
    - title: 'Administer'
      pages:
        - title: 'Overview'
          path: '/process-automation/latest/admin/'
        - title: 'Project deployment'
          path: '/process-automation/latest/admin/release/'
        - title: 'Process administration'
          path: '/process-automation/latest/admin/monitor/'
        - title: 'Users and groups'
          path: '/process-automation/latest/admin/users/'
        - title: 'Architecture'
          path: '/process-automation/latest/admin/architecture/'
    - title: 'Using'
      path: '/process-automation/latest/using/'
    - title: 'Develop'
      path: '/process-automation/latest/develop/'
