name: CI

on:
  push:
    branches:
      - master

env:
  BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}
  DISTRIBUTION_ID: ${{ secrets.STAGING_DISTRIBUTION_ID }}
  RUNNER_ROLE: ${{ secrets.EAD_PRODUCTION_RUNNER_ROLE }}
  RUNNER_EXTERNAL_ID: ${{ secrets.EAD_PROD_RUNNER_EXTERNAL_ID }}

jobs:
  jekyll-deploy:
    
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run Jekyll Build
      uses: ./.github/actions/jekyll_build
    - name: Run S3 Sync
      uses: ./.github/actions/s3_sync